# Generated by Django 4.2.23 on 2025-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_volunteers',
            field=models.PositiveIntegerField(default=1, help_text='Current number of volunteers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of volunteers allowed'),
        ),
    ]
