# Generated by Django 4.2.23 on 2025-07-31 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteersignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersignup',
            name='signed_up_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
